# Generated by Django 5.0.4 on 2024-04-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Group Name')),
                ('picture_path', models.TextField(default='https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg', verbose_name='Picture Path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chat',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('chatId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_chat', to='api.chat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
                'ordering': [],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='lastMessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_last_message', to='api.message'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('username', models.CharField(max_length=255, verbose_name='Name')),
                ('password', models.CharField(max_length=255, verbose_name='Name')),
                ('picture', models.TextField(default='https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg', verbose_name='Picture Path')),
                ('resizedPicture', models.TextField(default='https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg', verbose_name='Picture Path')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='api.chat')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': [],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender', to='api.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_admin', to='api.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='chat_users', to='api.user'),
        ),
    ]
