# Generated by Django 5.0.4 on 2024-04-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resizedPicture',
        ),
    ]
