# Generated by Django 5.0.4 on 2024-04-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_resizedpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='lastMessage',
        ),
    ]
