# Generated by Django 5.0.4 on 2024-04-26 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_createdat_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chatId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_chat', to='api.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_sender', to='api.user'),
        ),
    ]
